### ISSUE TITLE
Confusing failure when the wrong secret size is provided

### ISSUE THREAD

**Issue by dylanpyle** [hazae41/deno-aes-cfb#1]
Hey - thanks for the work on this module!

I ran into an issue where I was inadvertently passing the wrong size `secret` (36 bytes instead of 32). This failed, as it should, but instead of a descriptive error message and a stack trace, the program simply prints

```
error: Uncaught Loop Error
```
— and exits.

The lack of stack trace meant it took me a while to figure out the cause; not sure if that's something to do with `wasm-pack`, but would be lovely to get something a little more descriptive here.

<details>
  <summary>Repro Steps</summary>
  <code><pre>
$ cat debug.ts
import { Aes256Cfb } from "./deps.ts";
const secretKey = "9a939cfd0aeb46cfaa2f4b294f7a9cbc1234";
const keyArray = new TextEncoder().encode(secretKey);
const iv = keyArray.slice(0, 16);
const cipher = new Aes256Cfb(keyArray, iv);

$ deno run --allow-net debug.ts
Check debug.ts
error: Uncaught Loop Error
  </pre></code>
</details>

**Comment by hazae41** [comment]
Fixed!
